resources:
  - name: the-time
    type: time
    source:
      interval: 30s

jobs:
  - name: what-is-the-time
    plan:
      - get: the-time
        trigger: true
      - task: show-the-time
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          inputs:
            - name: the-time
          run:
            path: cat
            args: ["the-time/input"]